###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Comeau, CS165
# Author:
#     Yiqi Wang
# Summary:
#     It is a lot of fun doing this it just take some time to jump around between files.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

