###############################################################
# Program:
#     Checkpoint 05b, Constructors
#     Brother Comeau, CS165
# Author:
#     Yiqi Wang
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : money.h money.cpp check05b.cpp
	g++ money.cpp check05b.cpp

